<?php

namespace TestingTimes\App\Repository;

use TestingTimes\App\Entities\User;
use TestingTimes\Persistence\Repository;

class UserRepository extends Repository
{
    public static string $model = User::class;

    public function index(?array $criteria = null, ?int $page = null, ?int $limit = null)
    {
        // todo: how to make it so the T. is not here
        $this->getQuery()->where('T.name = :name')->setParameter('name', 'han woolderink');

        return parent::index($criteria, $page, $limit); // TODO: Change the autogenerated stub
    }
}
