version: "3.8"
services:
  db-mysql:
    build:
      dockerfile: Dockerfile
      context: ./mysql
    command: mysqld --sql_mode=""
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/.mysql-data:/var/lib/mysql:cached
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testingtimes


  db-pgsql:
    build:
      dockerfile: Dockerfile
      context: ./postgres
    restart: always
    ports:
    - '5432:5432' 
    volumes:
     - ./postgres/.data:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testingtimes
      PGDATA: /var/lib/postgresql/data/testingtimes


  web:
    image: nginx
    ports:
    - 80:80
    volumes: 
    - ./nginx/sites:/etc/nginx/conf.d
    - ./logs/nginx:/var/log/nginx
    - ./backend:/var/www/backend


  backend:
    build:
      context: .
      dockerfile: php/Dockerfile-dev
    volumes:
    - ./backend:/var/www/backend
    - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini