version: "3.8"
services:
  web:
    image: nginx
    ports:
    - 80:80
    volumes: 
    - ./nginx/sites:/etc/nginx/conf.d
    - ./logs/nginx:/var/log/nginx
    - ./backend:/var/www/backend
  backend:
    build:
      context: .
      dockerfile: php/Dockerfile-dev
    volumes:
    - ./backend:/var/www/backend
    - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini